### ISSUE TITLE
Status ??

### ISSUE THREAD

**Issue by fgrcon** [redomino/redomino.contentwellportlets#1]
extremely useful addon so far. Is this the main development line now?
Are there any adaptaions planned  in respect to plone.app.toolbar?
...
k.R. 
Franz

**Comment by davidemoro** [comment]
Il 20/09/2013 14:34, Franz Gerhard Reinisch ha scritto:

> extremely useful addon so far. Is this the main development line now?
> Are there any adaptaions planned in respect to plone.app.toolbar?

Hi,

you should consider the original implementation with the Products 
namespace. Now it was shipped with the redomino.contentwellportlets 
fixes, included in 4.2.0 and 4.2.1 version:
https://pypi.python.org/pypi/Products.ContentWellPortlets

This product exists only because we needed a public release with our 
fixes/changes and we wasn't able to get in touch for a long time with 
the original maintainer for including our patches.

Thank you.

davide moro

## 

Davide Moro
Technical Development Manager
http://linkedin.com/in/davidemoro82

Redomino Srl
http://redomino.com
HQ Largo Valgioie 14, Turin IT
Phone +39 0117499875
